baseurl:
title:		Ideal Image Slider
tagline:	Responsive Image Slider for Javascript &amp; WordPress
author:     Gilbert Pellegrom

permalink:  pretty

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jekyll-redirect-from
